AWSTemplateFormatVersion: 2010-09-09
Description: |
    Kittens Carousel is a static website application deployed with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.
Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ab4d1e9cf9a1215a
      InstanceType: t2.micro
      KeyName: EC2_key
      SecurityGroups:
        - !Ref Hamidsecgroup
      Tags:
        - Key: Name
          Value : Web Server of StackName
      UserData:
        Fn::Base64:
          !Sub |  
            #!/bin/bash

            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/hamidgokce/MY_PROJECTS/main/aws/projects/Project-101-kittens-carousel-static-website-ec2/static-web"
            cd /var/www/html
            wget $FOLDER/index.html
            wget $FOLDER/cat0.jpg
            wget $FOLDER/cat1.jpg
            wget $FOLDER/cat2.jpg
            wget $FOLDER/cat3.png
            systemctl start httpd
            systemctl enable httpd
  Hamidsecgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "String" # Required       
      SecurityGroupIngress: # merhaba
        - IpProtocol: tcp 
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyEC2.PublicDnsName # bir ozelligini cekme public dns getir
    Description: Kittens Carousel Application URL

    